logging:
  file:
    name: /tmp/logs/brp-api-gezag.json
  file-masked:
    name: /tmp/logs/brp-api-gezag.masked.json
  group:
    gezag: nl.rijksoverheid.mev
server:
  port: 8080

spring:
  application:
    name: brp-api-gezag
  config:
    import: classpath:META-INF/build-info.properties
  jooq:
    sql-dialect: postgres
  profiles:
    group:
      default: real-brp
      ont: fake-brp
      pre: real-brp
      prd: real-brp

management:
  endpoints:
    web:
      exposure:
        include: "*"

correlation:
  component-id: 02

---

spring:
  config:
    activate:
      on-profile: default
    import: classpath:developer.yml
