app:
  features:
    brp:
      dataset-path: src/test/resources/fixtures/persoonslijsten/GegenereerdUitExcelData/CGR_testbestand-20230525
    refactored-gezag:
      enabled: true

logging:
  level:
    nl.rijksoverheid.mev: DEBUG

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rvig_brp_api_testdata
    username: root
    password: root
