logging:
  file:
    name: build/brp-api-gezag.json
  file-masked:
    name: build/brp-api-gezag.masked.json
  level:
    nl.rijksoverheid.mev: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rvig_brp_api_testdata
    username: postgres
    password: postgres
