app:
  features:
    brp:
      dataset-path: src/test/resources/fixtures/persoonslijsten/GegenereerdUitExcelData/CGR_testbestand-20230525

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./tmp/mydb
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

new-gezag-service:
  enabled: true