openapi: 3.1.0
info:
  title: BRP API Gezagmodule
  description: >-
    De Gezagsmodule kan worden bevraagd op basis van één of meerdere BSNs

    - Gezag bepalen: input bsn(s) 
    
    Het antwoord van de Gezagsmodule komt in de vorm van een lijst met daarin de BSN minderjarige, Soort
    Gezagt tussen relatie met meerderjarige en BSN meerderjarige
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/v1/opvragenBevoegdheidTotGezag:
    post:
      tags:
        - GezagsmoduleInterface
      description: >-
        De volgende situaties kunnen (gelijktijdig) voorkomen:
        
        - Bij aanwezigheid van juridische kinderen wordt het gezag van deze persoon over diens kinderen teruggegeven. Het kan zijn dat omwille van het reduceren van BRP bevragingen de leeftijd van de kinderen uit de lijst met kinderen van de ouder wordt gebruikt om kinderen die al de leeftijd van 18 hebben bereikt niet te bevragen. dit heeft wel impact op de als minderjarige overleden kinderen; daar wordt dan geen gezagsuitspraak gedaan.
        
        - Is de persoon minderjarig dan wordt het gezag van de ouder(s) over deze persoon teruggegeven.
      operationId: opvragenBevoegdheidTotGezag
      parameters:
        - name: OIN
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GezagRequest'
        required: true
      responses:
        '200':
          description: OK
          headers:
            TransactionID:
              description: UUID gegenereerd voor de transactie
              style: simple
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GezagQueryResponse'
        '503':
          description: Gegevensbron niet beschikbaar
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    GezagRequest:
      type: object
      properties:
        bsns:
          type: array
          items:
            type: string
    GezagQueryResponse:
      type: object
      required:
        - type
      discriminator:
        propertyName: type
        mapping:
          RaadpleegGezag: '#/components/schemas/GezagResponse'
      properties:
        type:
          type: string
    GezagResponse:
      allOf:
        - $ref: '#/components/schemas/GezagQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              description: |
                * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
              items:
                $ref: 'persoon.yaml#/components/schemas/Persoon'
