openapi: 3.0.1
info:
  title: Persoonsgegevens API
  description: >-
    De persoonsgegevens api maakt het mogelijk persoonsgegevens op te vragen voor een persoon die nodig zijn voor het bepalen van bevoegdheden
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/v1/getPersoonsgegevens:
    post:
      tags:
        - Persoonsgegevens- V1
      summary: Opvragen persoonsgegevens van Vertegenwoordigde 
      description: >-
        Op basis van een bsn worden persoonsgegevens opgevraagd
      operationId: getPersoonsgegevens
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersoonsgegevensRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersoonsgegevensResultaaat'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
        '503':
          description: Gegevensbron niet beschikbaar
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    PersoonsgegevensRequest:
      type: object
      properties:
        vertegenwoordiger:
          $ref: '#/components/schemas/Identificatie'
        vertegenwoordigde:
          $ref: '#/components/schemas/Identificatie'
    Identificatie:
      type: object
      properties:
        identificatieNummer:
          type: string
        identificatieSoort:
          type: string
    Persoonsgegevens:
      type: object
      properties:
        bsn:
          type: string
        voornamen:
          type: string
        voorvoegsel:
          type: string
        geslachtsnaam:
          type: string
        geboortedatum:
          type: string
        opschortReden:
          type: string
        opschortDatum:
          type: string
    PersoonsgegevensResultaaat:
      type: object
      properties:
        persoonsgegevensList:
          type: array
          items:
            $ref: '#/components/schemas/Persoonsgegevens'