name: Deployment CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'deploy OCI image with tag'
        required: true
        type: string
      environment:
        description: 'to environment (acc|lap|prd)'
        required: true
        type: string

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy OCI image (no actual deployment, tags only)
        run: |
          docker pull ghcr.io/brp-api/brp-api-gezag:${{ inputs.tag }}
          docker tag ghcr.io/brp-api/brp-api-gezag:${{ inputs.tag }} ghcr.io/brp-api/brp-api-gezag:${{ inputs.environment }}
          echo "Status: pushing ghcr.io/brp-api/brp-api-gezag:${{ inputs.environment }}"
          docker push ghcr.io/brp-api/brp-api-gezag:${{ inputs.environment }}
