name: Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
      if: github.ref == 'refs/heads/main'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build OCI image
      if: github.ref != 'refs/heads/main'
      run: ./gradlew bootBuildImage
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build OCI image and publish it to GitHub Packages
      if: github.ref == 'refs/heads/main'
      run: ./gradlew bootBuildImage --publishImage
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Cucumber
      uses: ./.github/actions/run-cucumber
