name: tag and release to acc 

on:
  workflow_dispatch:
    inputs:
      commitSha:
        description: 'commit sha'
        required: true
        default: ''
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/acc',
              sha: ${{ inputs.commitSha }}
            }) 
#      - uses: actions/checkout@v4
#        with: 
#          ref: ${{ inputs.commitSha }}            
#      - name: Build and tag image
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
