name: tag and release to acc 

on:
  workflow_dispatch:
    inputs:
      commitSha:
        description: 'commit sha'
        required: true
        default: ''
        type: string

jobs:
  tag-commit:
    runs-on: ubuntu-latest      
    steps:  
      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: | 
              git status
#              git tag -a acc ${{ inputs.commitSha }} -m "tag acc"
#              git tag      
#              git push --tags https://root:$secrets.GITHUB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:main
#      - uses: actions/checkout@v4
#        with: 
#          ref: ${{ inputs.commitSha }}            
#      - name: Build and tag image
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
